### ISSUE TITLE
West Hardwood patch doesn't show icon

### ISSUE THREAD

**Issue by mxiia** [AbusiveTuna/DidICompost#2]
![image](https://user-images.githubusercontent.com/5335202/221730930-e26b4816-5775-4d72-8dae-f63ee454d91a.png)

**Comment by mxiia** [comment]
Ok, it's not the individual patch, because I just did it again and it was the center patch.

Composted all 3, center one didn't have the icon, went to recompost and got the "already treated" message which triggered the icon

**Comment by AbusiveTuna** [comment]
Super odd. There was an early issue where if you clicked on something like seeds, or saplings, before the compost animation was a tick into its animation that it would break. This is just because its using menu entries as a way to grab the patch, so the ID was switching to whatever you were clicking in your inventory. 

So I'm wondering if this issue still happens sometimes. Maybe because of something at the hardwood patches, or because of the way you normally plant hardwood trees? I'll have to play around a bit with these patches and see if I can recreate it

**Comment by mxiia** [comment]
that sounds very close to what i've noticed. It seems it's happens when i interrupt the composting animation before it finishes
